# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KE_aTLGmBVBymqc9rsN6iJPjzlJFzgcC
"""

happy_df = v2[v2['Mood'] == 'Happy']
angry_df = v2[v2['Mood'] == 'Angry']
sad_df = v2[v2['Mood'] == 'Sad']
heartbreak_df = v2[v2['Mood'] == 'Heartbreak']
focus_df = v2[v2['Mood'] == 'Focus']
selflove_df = v2[v2['Mood'] == 'Self Love']
inspiration_df = v2[v2['Mood'] == 'Inspiration']
party_df = v2[v2['Mood'] == 'Party']
love_df = v2[v2['Mood'] == 'Love']
friendship_df = v2[v2['Mood'] == 'Friendship']

happy_songs = happy_df[['Track']]
angry_songs = angry_df[['Track']]
sad_songs = sad_df[['Track']]
heartbreak_songs = heartbreak_df[['Track']]
focus_songs = focus_df[['Track']]
selflove_songs = selflove_df[['Track']]
inspiration_songs = inspiration_df[['Track']]
party_songs = party_df[['Track']]
love_songs = love_df[['Track']]
friendship_songs = friendship_df[['Track']]

def create_playlist(user_string):
    tracks = []
    for x in get_string(user_string):
        if x == 'happiness':
            tracks+=happy_songs.sample(30//len(get_string(user_string)))['Track'].to_list()
        if x == 'anger':
            tracks+=angry_songs.sample(30//len(get_string(user_string)))['Track'].to_list()
        if x == 'sadness':
            tracks+=sad_songs.sample(30//len(get_string(user_string)))['Track'].to_list()
        if x == 'heartbroken':
            tracks+=heartbreak_songs.sample(30//len(get_string(user_string)))['Track'].to_list()
        if x == 'working':
            tracks+=focus_songs.sample(30//len(get_string(user_string)))['Track'].to_list()
        if x == 'worry':
            tracks+=selflove_songs.sample(30//len(get_string(user_string)))['Track'].to_list()
        if x == 'boredom':
            tracks+=inspiration_songs.sample(30//len(get_string(user_string)))['Track'].to_list()
        if x == 'fun':
            tracks+=party_songs.sample(30//len(get_string(user_string)))['Track'].to_list()
        if x == 'love':
            tracks+=love_songs.sample(30//len(get_string(user_string)))['Track'].to_list()
        if x == 'lonely':
            tracks+=friendship_songs.sample(30//len(get_string(user_string)))['Track'].to_list()
    return tracks

create_playlist(user_string)

#I'm happy. I went to disneyland and hugged mickey which made me happy. Life is so good I'm so happy omg.