# -*- coding: utf-8 -*-
"""Get_String.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mt6cdu_h7BthsZXpy7UeM2f_k9nPvwUe
"""



import spacy
nlp = spacy.load("en_core_web_sm")
import re
import string
from textblob import TextBlob
from textblob.classifiers import NaiveBayesClassifier

import nltk
nltk.download('punkt')
import pandas as pd
alphabets= "([A-Za-z])"
prefixes = "(Mr|St|Mrs|Ms|Dr)[.]"
suffixes = "(Inc|Ltd|Jr|Sr|Co)"
starters = "(Mr|Mrs|Ms|Dr|He\s|She\s|It\s|They\s|Their\s|Our\s|We\s|But\s|However\s|That\s|This\s|Wherever)"
acronyms = "([A-Z][.][A-Z][.](?:[A-Z][.])?)"
websites = "[.](com|net|org|io|gov)"
def check_punctuation(text):
  if text[len(text)-1] in string.punctuation:
    print('yes')
    return text
  else:
    return text+'.'
def get_string(string):
  emotion_list=[]
  sents=split_into_sentences(string)
  for sent in sents:
    blob=TextBlob(sent,classifier=cl)
    emotion_list.append(blob.classify())
  return emotion_list
def split_into_sentences(text):
    text = check_punctuation(text) 
    print(text)
    text = " " + text + "  "
    text = text.replace("\n"," ")
    text = re.sub(prefixes,"\\1<prd>",text)
    text = re.sub(websites,"<prd>\\1",text)
    if "Ph.D" in text: text = text.replace("Ph.D.","Ph<prd>D<prd>")
    text = re.sub("\s" + alphabets + "[.] "," \\1<prd> ",text)
    text = re.sub(acronyms+" "+starters,"\\1<stop> \\2",text)
    text = re.sub(alphabets + "[.]" + alphabets + "[.]" + alphabets + "[.]","\\1<prd>\\2<prd>\\3<prd>",text)
    text = re.sub(alphabets + "[.]" + alphabets + "[.]","\\1<prd>\\2<prd>",text)
    text = re.sub(" "+suffixes+"[.] "+starters," \\1<stop> \\2",text)
    text = re.sub(" "+suffixes+"[.]"," \\1<prd>",text)
    text = re.sub(" " + alphabets + "[.]"," \\1<prd>",text)
    if "”" in text: text = text.replace(".”","”.")
    if "\"" in text: text = text.replace(".\"","\".")
    if "!" in text: text = text.replace("!\"","\"!")
    if "?" in text: text = text.replace("?\"","\"?")
    text = text.replace(".",".<stop>")
    text = text.replace("?","?<stop>")
    text = text.replace("!","!<stop>")
    text = text.replace("<prd>",".")
    sentences = text.split("<stop>")
    sentences = sentences[:-1]
    sentences = [s.strip() for s in sentences]
    return sentences

user_string=input("How do you feel?")


#  link to emotions_short.csv: https://drive.google.com/file/d/1Is6VaVft6BuL438byJQbePDA_Ys19v5W/view?usp=sharing


from textblob.classifiers import NaiveBayesClassifier
with open('/content/TECH-UB.0024_Final/TECH-Final-Frontend/emotion_complete.csv', encoding = "ISO-8859-1") as fp:
  cl = NaiveBayesClassifier(fp, format="csv")



print(get_string(user_string))

